baseURL = 'https://blog.404oops.com/'
languageCode = 'en-us'
title = "404's Blog"
theme = 'xmin'
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_cache$" ]
footnotereturnlinkcontents = "↩"

[permalinks]
note = "/note/:month/:day/:year/:slug/"
post = "/post/:month/:day/:year/:slug/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 2

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 3

[[menu.main]]
name = "Subscribe"
url = "index.xml"

[params]
description = "A programmer, Musician and nerd yapping."
footer = "&copy; [404oops](https://404oops.com) 2025 -- {Year}"
